apiVersion: v1
kind: Service
metadata:
  name: mysql-service-lb
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql


  # use "kubectl apply -f temp_expose.yaml"

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service-gen
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
